### PR TITLE
Wrapping Up

### PR DESCRIPTION
**Pull request by acderosas**
Just made sure some of the basic functionalities and Tests were working properly and code on this branch wasn't conflicting with main (as I was behind). See the second most recent commit for more info. Would have also liked to clean up the code (Excess html and separate out scripts/css) but I was limited by time.

// Fully consolidated adding a card functionalities created by David and Mark
// Merged tests in created by Matthew
// Worked off DB set up by Dexter but couldn't do more with it since it was indeed difficult to work with

### CODE REVIEW

**Comment by acderosas** [comment]
//Had to go back because I missed homepage and random card merge conflicts

**Review by PepperJam-Loser — APPROVED** [review]
passed tests, approving

**Comment by mcsharland** [comment]
Dang that was fast, beat me to the punch lol. 
Also Good work here

**Comment by acderosas** [comment]
// Fully consolidated adding a card functionalities created by David and Mark
// Merged tests in created by Matthew
// Worked off DB set up by Dexter but couldn't do more with it since it was indeed difficult to work with

**Pull request merged**
